/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * TeamPrompts.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateWorkspaceRequest,
  PostApiWorkspacesIdAvatarBody,
  UpdateWorkspaceRequest,
  WorkspaceDto
} from '../../model';

import { customInstance } from '../../../lib/api/axios-instance';
import type { ErrorType , BodyType } from '../../../lib/api/axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getApiWorkspaces = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<WorkspaceDto[]>(
      {url: `/api/workspaces`, method: 'GET', signal
    },
      options);
    }




export const getGetApiWorkspacesQueryKey = () => {
    return [
    `/api/workspaces`
    ] as const;
    }


export const getGetApiWorkspacesQueryOptions = <TData = Awaited<ReturnType<typeof getApiWorkspaces>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkspaces>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiWorkspacesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiWorkspaces>>> = ({ signal }) => getApiWorkspaces(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiWorkspaces>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiWorkspacesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiWorkspaces>>>
export type GetApiWorkspacesQueryError = ErrorType<unknown>


export function useGetApiWorkspaces<TData = Awaited<ReturnType<typeof getApiWorkspaces>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkspaces>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkspaces>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkspaces>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkspaces<TData = Awaited<ReturnType<typeof getApiWorkspaces>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkspaces>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkspaces>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkspaces>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkspaces<TData = Awaited<ReturnType<typeof getApiWorkspaces>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkspaces>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiWorkspaces<TData = Awaited<ReturnType<typeof getApiWorkspaces>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkspaces>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiWorkspacesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const postApiWorkspaces = (
    createWorkspaceRequest: BodyType<CreateWorkspaceRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<WorkspaceDto>(
      {url: `/api/workspaces`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createWorkspaceRequest, signal
    },
      options);
    }



export const getPostApiWorkspacesMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiWorkspaces>>, TError,{data: BodyType<CreateWorkspaceRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiWorkspaces>>, TError,{data: BodyType<CreateWorkspaceRequest>}, TContext> => {

const mutationKey = ['postApiWorkspaces'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiWorkspaces>>, {data: BodyType<CreateWorkspaceRequest>}> = (props) => {
          const {data} = props ?? {};

          return  postApiWorkspaces(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiWorkspacesMutationResult = NonNullable<Awaited<ReturnType<typeof postApiWorkspaces>>>
    export type PostApiWorkspacesMutationBody = BodyType<CreateWorkspaceRequest>
    export type PostApiWorkspacesMutationError = ErrorType<unknown>

    export const usePostApiWorkspaces = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiWorkspaces>>, TError,{data: BodyType<CreateWorkspaceRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiWorkspaces>>,
        TError,
        {data: BodyType<CreateWorkspaceRequest>},
        TContext
      > => {
      return useMutation(getPostApiWorkspacesMutationOptions(options), queryClient);
    }
    export const getApiWorkspacesId = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<WorkspaceDto>(
      {url: `/api/workspaces/${id}`, method: 'GET', signal
    },
      options);
    }




export const getGetApiWorkspacesIdQueryKey = (id: string,) => {
    return [
    `/api/workspaces/${id}`
    ] as const;
    }


export const getGetApiWorkspacesIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiWorkspacesId>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkspacesId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiWorkspacesIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiWorkspacesId>>> = ({ signal }) => getApiWorkspacesId(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiWorkspacesId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiWorkspacesIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiWorkspacesId>>>
export type GetApiWorkspacesIdQueryError = ErrorType<unknown>


export function useGetApiWorkspacesId<TData = Awaited<ReturnType<typeof getApiWorkspacesId>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkspacesId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkspacesId>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkspacesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkspacesId<TData = Awaited<ReturnType<typeof getApiWorkspacesId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkspacesId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkspacesId>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkspacesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkspacesId<TData = Awaited<ReturnType<typeof getApiWorkspacesId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkspacesId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiWorkspacesId<TData = Awaited<ReturnType<typeof getApiWorkspacesId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkspacesId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiWorkspacesIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const putApiWorkspacesId = (
    id: string,
    updateWorkspaceRequest: BodyType<UpdateWorkspaceRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<WorkspaceDto>(
      {url: `/api/workspaces/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateWorkspaceRequest, signal
    },
      options);
    }



export const getPutApiWorkspacesIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiWorkspacesId>>, TError,{id: string;data: BodyType<UpdateWorkspaceRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiWorkspacesId>>, TError,{id: string;data: BodyType<UpdateWorkspaceRequest>}, TContext> => {

const mutationKey = ['putApiWorkspacesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiWorkspacesId>>, {id: string;data: BodyType<UpdateWorkspaceRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiWorkspacesId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiWorkspacesIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiWorkspacesId>>>
    export type PutApiWorkspacesIdMutationBody = BodyType<UpdateWorkspaceRequest>
    export type PutApiWorkspacesIdMutationError = ErrorType<unknown>

    export const usePutApiWorkspacesId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiWorkspacesId>>, TError,{id: string;data: BodyType<UpdateWorkspaceRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiWorkspacesId>>,
        TError,
        {id: string;data: BodyType<UpdateWorkspaceRequest>},
        TContext
      > => {
      return useMutation(getPutApiWorkspacesIdMutationOptions(options), queryClient);
    }
    export const deleteApiWorkspacesId = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/workspaces/${id}`, method: 'DELETE', signal
    },
      options);
    }



export const getDeleteApiWorkspacesIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiWorkspacesId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiWorkspacesId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiWorkspacesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiWorkspacesId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiWorkspacesId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiWorkspacesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiWorkspacesId>>>

    export type DeleteApiWorkspacesIdMutationError = ErrorType<unknown>

    export const useDeleteApiWorkspacesId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiWorkspacesId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiWorkspacesId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteApiWorkspacesIdMutationOptions(options), queryClient);
    }
    export const postApiWorkspacesIdAvatar = (
    id: string,
    postApiWorkspacesIdAvatarBody: BodyType<PostApiWorkspacesIdAvatarBody>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {

      const formUrlEncoded = new URLSearchParams();
if(postApiWorkspacesIdAvatarBody.ContentType !== undefined) {
 formUrlEncoded.append(`ContentType`, postApiWorkspacesIdAvatarBody.ContentType);
 }
if(postApiWorkspacesIdAvatarBody.ContentDisposition !== undefined) {
 formUrlEncoded.append(`ContentDisposition`, postApiWorkspacesIdAvatarBody.ContentDisposition);
 }
if(postApiWorkspacesIdAvatarBody.Headers !== undefined) {
 formUrlEncoded.append(`Headers`, JSON.stringify(postApiWorkspacesIdAvatarBody.Headers));
 }
if(postApiWorkspacesIdAvatarBody.Length !== undefined) {
 formUrlEncoded.append(`Length`, postApiWorkspacesIdAvatarBody.Length.toString())
 }
if(postApiWorkspacesIdAvatarBody.Name !== undefined) {
 formUrlEncoded.append(`Name`, postApiWorkspacesIdAvatarBody.Name);
 }
if(postApiWorkspacesIdAvatarBody.FileName !== undefined) {
 formUrlEncoded.append(`FileName`, postApiWorkspacesIdAvatarBody.FileName);
 }

      return customInstance<WorkspaceDto>(
      {url: `/api/workspaces/${id}/avatar`, method: 'POST',
      headers: {'Content-Type': 'application/x-www-form-urlencoded', },
       data: formUrlEncoded, signal
    },
      options);
    }



export const getPostApiWorkspacesIdAvatarMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiWorkspacesIdAvatar>>, TError,{id: string;data: BodyType<PostApiWorkspacesIdAvatarBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiWorkspacesIdAvatar>>, TError,{id: string;data: BodyType<PostApiWorkspacesIdAvatarBody>}, TContext> => {

const mutationKey = ['postApiWorkspacesIdAvatar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiWorkspacesIdAvatar>>, {id: string;data: BodyType<PostApiWorkspacesIdAvatarBody>}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiWorkspacesIdAvatar(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiWorkspacesIdAvatarMutationResult = NonNullable<Awaited<ReturnType<typeof postApiWorkspacesIdAvatar>>>
    export type PostApiWorkspacesIdAvatarMutationBody = BodyType<PostApiWorkspacesIdAvatarBody>
    export type PostApiWorkspacesIdAvatarMutationError = ErrorType<unknown>

    export const usePostApiWorkspacesIdAvatar = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiWorkspacesIdAvatar>>, TError,{id: string;data: BodyType<PostApiWorkspacesIdAvatarBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiWorkspacesIdAvatar>>,
        TError,
        {id: string;data: BodyType<PostApiWorkspacesIdAvatarBody>},
        TContext
      > => {
      return useMutation(getPostApiWorkspacesIdAvatarMutationOptions(options), queryClient);
    }
    export const getApiWorkspacesIdAvatar = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/workspaces/${id}/avatar`, method: 'GET', signal
    },
      options);
    }




export const getGetApiWorkspacesIdAvatarQueryKey = (id: string,) => {
    return [
    `/api/workspaces/${id}/avatar`
    ] as const;
    }


export const getGetApiWorkspacesIdAvatarQueryOptions = <TData = Awaited<ReturnType<typeof getApiWorkspacesIdAvatar>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkspacesIdAvatar>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiWorkspacesIdAvatarQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiWorkspacesIdAvatar>>> = ({ signal }) => getApiWorkspacesIdAvatar(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiWorkspacesIdAvatar>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiWorkspacesIdAvatarQueryResult = NonNullable<Awaited<ReturnType<typeof getApiWorkspacesIdAvatar>>>
export type GetApiWorkspacesIdAvatarQueryError = ErrorType<unknown>


export function useGetApiWorkspacesIdAvatar<TData = Awaited<ReturnType<typeof getApiWorkspacesIdAvatar>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkspacesIdAvatar>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkspacesIdAvatar>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkspacesIdAvatar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkspacesIdAvatar<TData = Awaited<ReturnType<typeof getApiWorkspacesIdAvatar>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkspacesIdAvatar>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkspacesIdAvatar>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkspacesIdAvatar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkspacesIdAvatar<TData = Awaited<ReturnType<typeof getApiWorkspacesIdAvatar>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkspacesIdAvatar>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiWorkspacesIdAvatar<TData = Awaited<ReturnType<typeof getApiWorkspacesIdAvatar>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkspacesIdAvatar>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiWorkspacesIdAvatarQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






