/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * TeamPrompts.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateScriptVariantRequest,
  GetApiScriptProjectsParams,
  PostApiScriptProjectsBody,
  ScriptDto,
  ScriptProjectDto,
  ScriptProjectListItemDto,
  UpdateScriptProjectRequest
} from '../../model';

import { customInstance } from '../../../lib/api/axios-instance';
import type { ErrorType , BodyType } from '../../../lib/api/axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getApiScriptProjects = (
    params?: GetApiScriptProjectsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ScriptProjectListItemDto[]>(
      {url: `/api/script-projects`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiScriptProjectsQueryKey = (params?: GetApiScriptProjectsParams,) => {
    return [
    `/api/script-projects`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiScriptProjectsQueryOptions = <TData = Awaited<ReturnType<typeof getApiScriptProjects>>, TError = ErrorType<unknown>>(params?: GetApiScriptProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiScriptProjects>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiScriptProjectsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiScriptProjects>>> = ({ signal }) => getApiScriptProjects(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiScriptProjects>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiScriptProjectsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiScriptProjects>>>
export type GetApiScriptProjectsQueryError = ErrorType<unknown>


export function useGetApiScriptProjects<TData = Awaited<ReturnType<typeof getApiScriptProjects>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiScriptProjectsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiScriptProjects>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiScriptProjects>>,
          TError,
          Awaited<ReturnType<typeof getApiScriptProjects>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiScriptProjects<TData = Awaited<ReturnType<typeof getApiScriptProjects>>, TError = ErrorType<unknown>>(
 params?: GetApiScriptProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiScriptProjects>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiScriptProjects>>,
          TError,
          Awaited<ReturnType<typeof getApiScriptProjects>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiScriptProjects<TData = Awaited<ReturnType<typeof getApiScriptProjects>>, TError = ErrorType<unknown>>(
 params?: GetApiScriptProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiScriptProjects>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiScriptProjects<TData = Awaited<ReturnType<typeof getApiScriptProjects>>, TError = ErrorType<unknown>>(
 params?: GetApiScriptProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiScriptProjects>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiScriptProjectsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const postApiScriptProjects = (
    postApiScriptProjectsBody: BodyType<PostApiScriptProjectsBody>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {

      const formUrlEncoded = new URLSearchParams();
if(postApiScriptProjectsBody.workspaceId !== undefined) {
 formUrlEncoded.append(`workspaceId`, postApiScriptProjectsBody.workspaceId);
 }

if(postApiScriptProjectsBody.ContentType !== undefined) {
 formUrlEncoded.append(`ContentType`, postApiScriptProjectsBody.ContentType);
 }
if(postApiScriptProjectsBody.ContentDisposition !== undefined) {
 formUrlEncoded.append(`ContentDisposition`, postApiScriptProjectsBody.ContentDisposition);
 }
if(postApiScriptProjectsBody.Headers !== undefined) {
 formUrlEncoded.append(`Headers`, JSON.stringify(postApiScriptProjectsBody.Headers));
 }
if(postApiScriptProjectsBody.Length !== undefined) {
 formUrlEncoded.append(`Length`, postApiScriptProjectsBody.Length.toString())
 }
if(postApiScriptProjectsBody.Name !== undefined) {
 formUrlEncoded.append(`Name`, postApiScriptProjectsBody.Name);
 }
if(postApiScriptProjectsBody.FileName !== undefined) {
 formUrlEncoded.append(`FileName`, postApiScriptProjectsBody.FileName);
 }

if(postApiScriptProjectsBody.name !== undefined) {
 formUrlEncoded.append(`name`, postApiScriptProjectsBody.name);
 }

      return customInstance<ScriptProjectDto>(
      {url: `/api/script-projects`, method: 'POST',
      headers: {'Content-Type': 'application/x-www-form-urlencoded', },
       data: formUrlEncoded, signal
    },
      options);
    }



export const getPostApiScriptProjectsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiScriptProjects>>, TError,{data: BodyType<PostApiScriptProjectsBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiScriptProjects>>, TError,{data: BodyType<PostApiScriptProjectsBody>}, TContext> => {

const mutationKey = ['postApiScriptProjects'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiScriptProjects>>, {data: BodyType<PostApiScriptProjectsBody>}> = (props) => {
          const {data} = props ?? {};

          return  postApiScriptProjects(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiScriptProjectsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiScriptProjects>>>
    export type PostApiScriptProjectsMutationBody = BodyType<PostApiScriptProjectsBody>
    export type PostApiScriptProjectsMutationError = ErrorType<unknown>

    export const usePostApiScriptProjects = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiScriptProjects>>, TError,{data: BodyType<PostApiScriptProjectsBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiScriptProjects>>,
        TError,
        {data: BodyType<PostApiScriptProjectsBody>},
        TContext
      > => {
      return useMutation(getPostApiScriptProjectsMutationOptions(options), queryClient);
    }
    export const getApiScriptProjectsId = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ScriptProjectDto>(
      {url: `/api/script-projects/${id}`, method: 'GET', signal
    },
      options);
    }




export const getGetApiScriptProjectsIdQueryKey = (id: string,) => {
    return [
    `/api/script-projects/${id}`
    ] as const;
    }


export const getGetApiScriptProjectsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiScriptProjectsId>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiScriptProjectsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiScriptProjectsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiScriptProjectsId>>> = ({ signal }) => getApiScriptProjectsId(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiScriptProjectsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiScriptProjectsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiScriptProjectsId>>>
export type GetApiScriptProjectsIdQueryError = ErrorType<unknown>


export function useGetApiScriptProjectsId<TData = Awaited<ReturnType<typeof getApiScriptProjectsId>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiScriptProjectsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiScriptProjectsId>>,
          TError,
          Awaited<ReturnType<typeof getApiScriptProjectsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiScriptProjectsId<TData = Awaited<ReturnType<typeof getApiScriptProjectsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiScriptProjectsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiScriptProjectsId>>,
          TError,
          Awaited<ReturnType<typeof getApiScriptProjectsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiScriptProjectsId<TData = Awaited<ReturnType<typeof getApiScriptProjectsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiScriptProjectsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiScriptProjectsId<TData = Awaited<ReturnType<typeof getApiScriptProjectsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiScriptProjectsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiScriptProjectsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const putApiScriptProjectsId = (
    id: string,
    updateScriptProjectRequest: BodyType<UpdateScriptProjectRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ScriptProjectDto>(
      {url: `/api/script-projects/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateScriptProjectRequest, signal
    },
      options);
    }



export const getPutApiScriptProjectsIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiScriptProjectsId>>, TError,{id: string;data: BodyType<UpdateScriptProjectRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiScriptProjectsId>>, TError,{id: string;data: BodyType<UpdateScriptProjectRequest>}, TContext> => {

const mutationKey = ['putApiScriptProjectsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiScriptProjectsId>>, {id: string;data: BodyType<UpdateScriptProjectRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiScriptProjectsId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiScriptProjectsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiScriptProjectsId>>>
    export type PutApiScriptProjectsIdMutationBody = BodyType<UpdateScriptProjectRequest>
    export type PutApiScriptProjectsIdMutationError = ErrorType<unknown>

    export const usePutApiScriptProjectsId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiScriptProjectsId>>, TError,{id: string;data: BodyType<UpdateScriptProjectRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiScriptProjectsId>>,
        TError,
        {id: string;data: BodyType<UpdateScriptProjectRequest>},
        TContext
      > => {
      return useMutation(getPutApiScriptProjectsIdMutationOptions(options), queryClient);
    }
    export const deleteApiScriptProjectsId = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/script-projects/${id}`, method: 'DELETE', signal
    },
      options);
    }



export const getDeleteApiScriptProjectsIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiScriptProjectsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiScriptProjectsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiScriptProjectsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiScriptProjectsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiScriptProjectsId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiScriptProjectsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiScriptProjectsId>>>

    export type DeleteApiScriptProjectsIdMutationError = ErrorType<unknown>

    export const useDeleteApiScriptProjectsId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiScriptProjectsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiScriptProjectsId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteApiScriptProjectsIdMutationOptions(options), queryClient);
    }
    export const getApiScriptProjectsIdVariants = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ScriptDto[]>(
      {url: `/api/script-projects/${id}/variants`, method: 'GET', signal
    },
      options);
    }




export const getGetApiScriptProjectsIdVariantsQueryKey = (id: string,) => {
    return [
    `/api/script-projects/${id}/variants`
    ] as const;
    }


export const getGetApiScriptProjectsIdVariantsQueryOptions = <TData = Awaited<ReturnType<typeof getApiScriptProjectsIdVariants>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiScriptProjectsIdVariants>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiScriptProjectsIdVariantsQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiScriptProjectsIdVariants>>> = ({ signal }) => getApiScriptProjectsIdVariants(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiScriptProjectsIdVariants>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiScriptProjectsIdVariantsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiScriptProjectsIdVariants>>>
export type GetApiScriptProjectsIdVariantsQueryError = ErrorType<unknown>


export function useGetApiScriptProjectsIdVariants<TData = Awaited<ReturnType<typeof getApiScriptProjectsIdVariants>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiScriptProjectsIdVariants>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiScriptProjectsIdVariants>>,
          TError,
          Awaited<ReturnType<typeof getApiScriptProjectsIdVariants>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiScriptProjectsIdVariants<TData = Awaited<ReturnType<typeof getApiScriptProjectsIdVariants>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiScriptProjectsIdVariants>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiScriptProjectsIdVariants>>,
          TError,
          Awaited<ReturnType<typeof getApiScriptProjectsIdVariants>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiScriptProjectsIdVariants<TData = Awaited<ReturnType<typeof getApiScriptProjectsIdVariants>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiScriptProjectsIdVariants>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiScriptProjectsIdVariants<TData = Awaited<ReturnType<typeof getApiScriptProjectsIdVariants>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiScriptProjectsIdVariants>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiScriptProjectsIdVariantsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const postApiScriptProjectsIdVariants = (
    id: string,
    createScriptVariantRequest: BodyType<CreateScriptVariantRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ScriptDto>(
      {url: `/api/script-projects/${id}/variants`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createScriptVariantRequest, signal
    },
      options);
    }



export const getPostApiScriptProjectsIdVariantsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiScriptProjectsIdVariants>>, TError,{id: string;data: BodyType<CreateScriptVariantRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiScriptProjectsIdVariants>>, TError,{id: string;data: BodyType<CreateScriptVariantRequest>}, TContext> => {

const mutationKey = ['postApiScriptProjectsIdVariants'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiScriptProjectsIdVariants>>, {id: string;data: BodyType<CreateScriptVariantRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiScriptProjectsIdVariants(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiScriptProjectsIdVariantsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiScriptProjectsIdVariants>>>
    export type PostApiScriptProjectsIdVariantsMutationBody = BodyType<CreateScriptVariantRequest>
    export type PostApiScriptProjectsIdVariantsMutationError = ErrorType<unknown>

    export const usePostApiScriptProjectsIdVariants = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiScriptProjectsIdVariants>>, TError,{id: string;data: BodyType<CreateScriptVariantRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiScriptProjectsIdVariants>>,
        TError,
        {id: string;data: BodyType<CreateScriptVariantRequest>},
        TContext
      > => {
      return useMutation(getPostApiScriptProjectsIdVariantsMutationOptions(options), queryClient);
    }
    export const postApiScriptProjectsIdVariantsVariantIdPromote = (
    id: string,
    variantId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ScriptProjectDto>(
      {url: `/api/script-projects/${id}/variants/${variantId}/promote`, method: 'POST', signal
    },
      options);
    }



export const getPostApiScriptProjectsIdVariantsVariantIdPromoteMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiScriptProjectsIdVariantsVariantIdPromote>>, TError,{id: string;variantId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiScriptProjectsIdVariantsVariantIdPromote>>, TError,{id: string;variantId: string}, TContext> => {

const mutationKey = ['postApiScriptProjectsIdVariantsVariantIdPromote'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiScriptProjectsIdVariantsVariantIdPromote>>, {id: string;variantId: string}> = (props) => {
          const {id,variantId} = props ?? {};

          return  postApiScriptProjectsIdVariantsVariantIdPromote(id,variantId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiScriptProjectsIdVariantsVariantIdPromoteMutationResult = NonNullable<Awaited<ReturnType<typeof postApiScriptProjectsIdVariantsVariantIdPromote>>>

    export type PostApiScriptProjectsIdVariantsVariantIdPromoteMutationError = ErrorType<unknown>

    export const usePostApiScriptProjectsIdVariantsVariantIdPromote = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiScriptProjectsIdVariantsVariantIdPromote>>, TError,{id: string;variantId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiScriptProjectsIdVariantsVariantIdPromote>>,
        TError,
        {id: string;variantId: string},
        TContext
      > => {
      return useMutation(getPostApiScriptProjectsIdVariantsVariantIdPromoteMutationOptions(options), queryClient);
    }
    export const deleteApiScriptProjectsIdVariantsVariantId = (
    id: string,
    variantId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/script-projects/${id}/variants/${variantId}`, method: 'DELETE', signal
    },
      options);
    }



export const getDeleteApiScriptProjectsIdVariantsVariantIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiScriptProjectsIdVariantsVariantId>>, TError,{id: string;variantId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiScriptProjectsIdVariantsVariantId>>, TError,{id: string;variantId: string}, TContext> => {

const mutationKey = ['deleteApiScriptProjectsIdVariantsVariantId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiScriptProjectsIdVariantsVariantId>>, {id: string;variantId: string}> = (props) => {
          const {id,variantId} = props ?? {};

          return  deleteApiScriptProjectsIdVariantsVariantId(id,variantId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiScriptProjectsIdVariantsVariantIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiScriptProjectsIdVariantsVariantId>>>

    export type DeleteApiScriptProjectsIdVariantsVariantIdMutationError = ErrorType<unknown>

    export const useDeleteApiScriptProjectsIdVariantsVariantId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiScriptProjectsIdVariantsVariantId>>, TError,{id: string;variantId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiScriptProjectsIdVariantsVariantId>>,
        TError,
        {id: string;variantId: string},
        TContext
      > => {
      return useMutation(getDeleteApiScriptProjectsIdVariantsVariantIdMutationOptions(options), queryClient);
    }
