/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * TeamPrompts.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ModelDto,
  SetApiKeyRequest,
  SetDefaultModelRequest,
  SettingsDto
} from '../../model';

import { customInstance } from '../../../lib/api/axios-instance';
import type { ErrorType , BodyType } from '../../../lib/api/axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getApiSettings = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<SettingsDto>(
      {url: `/api/settings`, method: 'GET', signal
    },
      options);
    }




export const getGetApiSettingsQueryKey = () => {
    return [
    `/api/settings`
    ] as const;
    }


export const getGetApiSettingsQueryOptions = <TData = Awaited<ReturnType<typeof getApiSettings>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSettings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiSettingsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiSettings>>> = ({ signal }) => getApiSettings(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiSettings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiSettingsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiSettings>>>
export type GetApiSettingsQueryError = ErrorType<unknown>


export function useGetApiSettings<TData = Awaited<ReturnType<typeof getApiSettings>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSettings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSettings>>,
          TError,
          Awaited<ReturnType<typeof getApiSettings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSettings<TData = Awaited<ReturnType<typeof getApiSettings>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSettings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSettings>>,
          TError,
          Awaited<ReturnType<typeof getApiSettings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSettings<TData = Awaited<ReturnType<typeof getApiSettings>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSettings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiSettings<TData = Awaited<ReturnType<typeof getApiSettings>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSettings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiSettingsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApiSettingsModels = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ModelDto[]>(
      {url: `/api/settings/models`, method: 'GET', signal
    },
      options);
    }




export const getGetApiSettingsModelsQueryKey = () => {
    return [
    `/api/settings/models`
    ] as const;
    }


export const getGetApiSettingsModelsQueryOptions = <TData = Awaited<ReturnType<typeof getApiSettingsModels>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSettingsModels>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiSettingsModelsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiSettingsModels>>> = ({ signal }) => getApiSettingsModels(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiSettingsModels>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiSettingsModelsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiSettingsModels>>>
export type GetApiSettingsModelsQueryError = ErrorType<unknown>


export function useGetApiSettingsModels<TData = Awaited<ReturnType<typeof getApiSettingsModels>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSettingsModels>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSettingsModels>>,
          TError,
          Awaited<ReturnType<typeof getApiSettingsModels>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSettingsModels<TData = Awaited<ReturnType<typeof getApiSettingsModels>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSettingsModels>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSettingsModels>>,
          TError,
          Awaited<ReturnType<typeof getApiSettingsModels>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSettingsModels<TData = Awaited<ReturnType<typeof getApiSettingsModels>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSettingsModels>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiSettingsModels<TData = Awaited<ReturnType<typeof getApiSettingsModels>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSettingsModels>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiSettingsModelsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const putApiSettingsApiKey = (
    setApiKeyRequest: BodyType<SetApiKeyRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/settings/api-key`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: setApiKeyRequest, signal
    },
      options);
    }



export const getPutApiSettingsApiKeyMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiSettingsApiKey>>, TError,{data: BodyType<SetApiKeyRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiSettingsApiKey>>, TError,{data: BodyType<SetApiKeyRequest>}, TContext> => {

const mutationKey = ['putApiSettingsApiKey'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiSettingsApiKey>>, {data: BodyType<SetApiKeyRequest>}> = (props) => {
          const {data} = props ?? {};

          return  putApiSettingsApiKey(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiSettingsApiKeyMutationResult = NonNullable<Awaited<ReturnType<typeof putApiSettingsApiKey>>>
    export type PutApiSettingsApiKeyMutationBody = BodyType<SetApiKeyRequest>
    export type PutApiSettingsApiKeyMutationError = ErrorType<unknown>

    export const usePutApiSettingsApiKey = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiSettingsApiKey>>, TError,{data: BodyType<SetApiKeyRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiSettingsApiKey>>,
        TError,
        {data: BodyType<SetApiKeyRequest>},
        TContext
      > => {
      return useMutation(getPutApiSettingsApiKeyMutationOptions(options), queryClient);
    }
    export const putApiSettingsDefaultModel = (
    setDefaultModelRequest: BodyType<SetDefaultModelRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/settings/default-model`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: setDefaultModelRequest, signal
    },
      options);
    }



export const getPutApiSettingsDefaultModelMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiSettingsDefaultModel>>, TError,{data: BodyType<SetDefaultModelRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiSettingsDefaultModel>>, TError,{data: BodyType<SetDefaultModelRequest>}, TContext> => {

const mutationKey = ['putApiSettingsDefaultModel'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiSettingsDefaultModel>>, {data: BodyType<SetDefaultModelRequest>}> = (props) => {
          const {data} = props ?? {};

          return  putApiSettingsDefaultModel(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiSettingsDefaultModelMutationResult = NonNullable<Awaited<ReturnType<typeof putApiSettingsDefaultModel>>>
    export type PutApiSettingsDefaultModelMutationBody = BodyType<SetDefaultModelRequest>
    export type PutApiSettingsDefaultModelMutationError = ErrorType<unknown>

    export const usePutApiSettingsDefaultModel = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiSettingsDefaultModel>>, TError,{data: BodyType<SetDefaultModelRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiSettingsDefaultModel>>,
        TError,
        {data: BodyType<SetDefaultModelRequest>},
        TContext
      > => {
      return useMutation(getPutApiSettingsDefaultModelMutationOptions(options), queryClient);
    }
    export const postApiSettingsModelsRefresh = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ModelDto[]>(
      {url: `/api/settings/models/refresh`, method: 'POST', signal
    },
      options);
    }



export const getPostApiSettingsModelsRefreshMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSettingsModelsRefresh>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiSettingsModelsRefresh>>, TError,void, TContext> => {

const mutationKey = ['postApiSettingsModelsRefresh'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiSettingsModelsRefresh>>, void> = () => {


          return  postApiSettingsModelsRefresh(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiSettingsModelsRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof postApiSettingsModelsRefresh>>>

    export type PostApiSettingsModelsRefreshMutationError = ErrorType<unknown>

    export const usePostApiSettingsModelsRefresh = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSettingsModelsRefresh>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiSettingsModelsRefresh>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiSettingsModelsRefreshMutationOptions(options), queryClient);
    }
