/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * TeamPrompts.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiScriptsParams,
  PostApiScriptsBody,
  ScriptDto,
  ScriptListItemDto,
  SessionWithResultsDto,
  TrayItemDto,
  UpdateScriptRequest
} from '../../model';

import { customInstance } from '../../../lib/api/axios-instance';
import type { ErrorType , BodyType } from '../../../lib/api/axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getApiScripts = (
    params?: GetApiScriptsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ScriptListItemDto[]>(
      {url: `/api/scripts`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiScriptsQueryKey = (params?: GetApiScriptsParams,) => {
    return [
    `/api/scripts`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiScriptsQueryOptions = <TData = Awaited<ReturnType<typeof getApiScripts>>, TError = ErrorType<unknown>>(params?: GetApiScriptsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiScripts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiScriptsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiScripts>>> = ({ signal }) => getApiScripts(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiScripts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiScriptsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiScripts>>>
export type GetApiScriptsQueryError = ErrorType<unknown>


export function useGetApiScripts<TData = Awaited<ReturnType<typeof getApiScripts>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiScriptsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiScripts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiScripts>>,
          TError,
          Awaited<ReturnType<typeof getApiScripts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiScripts<TData = Awaited<ReturnType<typeof getApiScripts>>, TError = ErrorType<unknown>>(
 params?: GetApiScriptsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiScripts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiScripts>>,
          TError,
          Awaited<ReturnType<typeof getApiScripts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiScripts<TData = Awaited<ReturnType<typeof getApiScripts>>, TError = ErrorType<unknown>>(
 params?: GetApiScriptsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiScripts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiScripts<TData = Awaited<ReturnType<typeof getApiScripts>>, TError = ErrorType<unknown>>(
 params?: GetApiScriptsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiScripts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiScriptsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const postApiScripts = (
    postApiScriptsBody: BodyType<PostApiScriptsBody>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {

      const formUrlEncoded = new URLSearchParams();
if(postApiScriptsBody.ContentType !== undefined) {
 formUrlEncoded.append(`ContentType`, postApiScriptsBody.ContentType);
 }
if(postApiScriptsBody.ContentDisposition !== undefined) {
 formUrlEncoded.append(`ContentDisposition`, postApiScriptsBody.ContentDisposition);
 }
if(postApiScriptsBody.Headers !== undefined) {
 formUrlEncoded.append(`Headers`, JSON.stringify(postApiScriptsBody.Headers));
 }
if(postApiScriptsBody.Length !== undefined) {
 formUrlEncoded.append(`Length`, postApiScriptsBody.Length.toString())
 }
if(postApiScriptsBody.Name !== undefined) {
 formUrlEncoded.append(`Name`, postApiScriptsBody.Name);
 }
if(postApiScriptsBody.FileName !== undefined) {
 formUrlEncoded.append(`FileName`, postApiScriptsBody.FileName);
 }

if(postApiScriptsBody.name !== undefined) {
 formUrlEncoded.append(`name`, postApiScriptsBody.name);
 }

      return customInstance<ScriptDto>(
      {url: `/api/scripts`, method: 'POST',
      headers: {'Content-Type': 'application/x-www-form-urlencoded', },
       data: formUrlEncoded, signal
    },
      options);
    }



export const getPostApiScriptsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiScripts>>, TError,{data: BodyType<PostApiScriptsBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiScripts>>, TError,{data: BodyType<PostApiScriptsBody>}, TContext> => {

const mutationKey = ['postApiScripts'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiScripts>>, {data: BodyType<PostApiScriptsBody>}> = (props) => {
          const {data} = props ?? {};

          return  postApiScripts(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiScriptsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiScripts>>>
    export type PostApiScriptsMutationBody = BodyType<PostApiScriptsBody>
    export type PostApiScriptsMutationError = ErrorType<unknown>

    export const usePostApiScripts = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiScripts>>, TError,{data: BodyType<PostApiScriptsBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiScripts>>,
        TError,
        {data: BodyType<PostApiScriptsBody>},
        TContext
      > => {
      return useMutation(getPostApiScriptsMutationOptions(options), queryClient);
    }
    export const getApiScriptsId = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ScriptDto>(
      {url: `/api/scripts/${id}`, method: 'GET', signal
    },
      options);
    }




export const getGetApiScriptsIdQueryKey = (id: string,) => {
    return [
    `/api/scripts/${id}`
    ] as const;
    }


export const getGetApiScriptsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiScriptsId>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiScriptsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiScriptsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiScriptsId>>> = ({ signal }) => getApiScriptsId(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiScriptsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiScriptsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiScriptsId>>>
export type GetApiScriptsIdQueryError = ErrorType<unknown>


export function useGetApiScriptsId<TData = Awaited<ReturnType<typeof getApiScriptsId>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiScriptsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiScriptsId>>,
          TError,
          Awaited<ReturnType<typeof getApiScriptsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiScriptsId<TData = Awaited<ReturnType<typeof getApiScriptsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiScriptsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiScriptsId>>,
          TError,
          Awaited<ReturnType<typeof getApiScriptsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiScriptsId<TData = Awaited<ReturnType<typeof getApiScriptsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiScriptsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiScriptsId<TData = Awaited<ReturnType<typeof getApiScriptsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiScriptsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiScriptsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const putApiScriptsId = (
    id: string,
    updateScriptRequest: BodyType<UpdateScriptRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ScriptDto>(
      {url: `/api/scripts/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateScriptRequest, signal
    },
      options);
    }



export const getPutApiScriptsIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiScriptsId>>, TError,{id: string;data: BodyType<UpdateScriptRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiScriptsId>>, TError,{id: string;data: BodyType<UpdateScriptRequest>}, TContext> => {

const mutationKey = ['putApiScriptsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiScriptsId>>, {id: string;data: BodyType<UpdateScriptRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiScriptsId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiScriptsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiScriptsId>>>
    export type PutApiScriptsIdMutationBody = BodyType<UpdateScriptRequest>
    export type PutApiScriptsIdMutationError = ErrorType<unknown>

    export const usePutApiScriptsId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiScriptsId>>, TError,{id: string;data: BodyType<UpdateScriptRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiScriptsId>>,
        TError,
        {id: string;data: BodyType<UpdateScriptRequest>},
        TContext
      > => {
      return useMutation(getPutApiScriptsIdMutationOptions(options), queryClient);
    }
    export const deleteApiScriptsId = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/scripts/${id}`, method: 'DELETE', signal
    },
      options);
    }



export const getDeleteApiScriptsIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiScriptsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiScriptsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiScriptsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiScriptsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiScriptsId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiScriptsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiScriptsId>>>

    export type DeleteApiScriptsIdMutationError = ErrorType<unknown>

    export const useDeleteApiScriptsId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiScriptsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiScriptsId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteApiScriptsIdMutationOptions(options), queryClient);
    }
    export const getApiScriptsIdSessions = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<SessionWithResultsDto[]>(
      {url: `/api/scripts/${id}/sessions`, method: 'GET', signal
    },
      options);
    }




export const getGetApiScriptsIdSessionsQueryKey = (id: string,) => {
    return [
    `/api/scripts/${id}/sessions`
    ] as const;
    }


export const getGetApiScriptsIdSessionsQueryOptions = <TData = Awaited<ReturnType<typeof getApiScriptsIdSessions>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiScriptsIdSessions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiScriptsIdSessionsQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiScriptsIdSessions>>> = ({ signal }) => getApiScriptsIdSessions(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiScriptsIdSessions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiScriptsIdSessionsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiScriptsIdSessions>>>
export type GetApiScriptsIdSessionsQueryError = ErrorType<unknown>


export function useGetApiScriptsIdSessions<TData = Awaited<ReturnType<typeof getApiScriptsIdSessions>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiScriptsIdSessions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiScriptsIdSessions>>,
          TError,
          Awaited<ReturnType<typeof getApiScriptsIdSessions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiScriptsIdSessions<TData = Awaited<ReturnType<typeof getApiScriptsIdSessions>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiScriptsIdSessions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiScriptsIdSessions>>,
          TError,
          Awaited<ReturnType<typeof getApiScriptsIdSessions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiScriptsIdSessions<TData = Awaited<ReturnType<typeof getApiScriptsIdSessions>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiScriptsIdSessions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiScriptsIdSessions<TData = Awaited<ReturnType<typeof getApiScriptsIdSessions>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiScriptsIdSessions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiScriptsIdSessionsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const deleteApiScriptsIdSessions = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/scripts/${id}/sessions`, method: 'DELETE', signal
    },
      options);
    }



export const getDeleteApiScriptsIdSessionsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiScriptsIdSessions>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiScriptsIdSessions>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiScriptsIdSessions'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiScriptsIdSessions>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiScriptsIdSessions(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiScriptsIdSessionsMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiScriptsIdSessions>>>

    export type DeleteApiScriptsIdSessionsMutationError = ErrorType<unknown>

    export const useDeleteApiScriptsIdSessions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiScriptsIdSessions>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiScriptsIdSessions>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteApiScriptsIdSessionsMutationOptions(options), queryClient);
    }
    export const getApiScriptsIdTray = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<TrayItemDto[]>(
      {url: `/api/scripts/${id}/tray`, method: 'GET', signal
    },
      options);
    }




export const getGetApiScriptsIdTrayQueryKey = (id: string,) => {
    return [
    `/api/scripts/${id}/tray`
    ] as const;
    }


export const getGetApiScriptsIdTrayQueryOptions = <TData = Awaited<ReturnType<typeof getApiScriptsIdTray>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiScriptsIdTray>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiScriptsIdTrayQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiScriptsIdTray>>> = ({ signal }) => getApiScriptsIdTray(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiScriptsIdTray>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiScriptsIdTrayQueryResult = NonNullable<Awaited<ReturnType<typeof getApiScriptsIdTray>>>
export type GetApiScriptsIdTrayQueryError = ErrorType<unknown>


export function useGetApiScriptsIdTray<TData = Awaited<ReturnType<typeof getApiScriptsIdTray>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiScriptsIdTray>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiScriptsIdTray>>,
          TError,
          Awaited<ReturnType<typeof getApiScriptsIdTray>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiScriptsIdTray<TData = Awaited<ReturnType<typeof getApiScriptsIdTray>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiScriptsIdTray>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiScriptsIdTray>>,
          TError,
          Awaited<ReturnType<typeof getApiScriptsIdTray>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiScriptsIdTray<TData = Awaited<ReturnType<typeof getApiScriptsIdTray>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiScriptsIdTray>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiScriptsIdTray<TData = Awaited<ReturnType<typeof getApiScriptsIdTray>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiScriptsIdTray>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiScriptsIdTrayQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






