/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * TeamPrompts.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export type ActivityTargetType = typeof ActivityTargetType[keyof typeof ActivityTargetType];


export const ActivityTargetType = {
  Script: 'Script',
  Prompt: 'Prompt',
  PromptVersion: 'PromptVersion',
  GenerationRun: 'GenerationRun',
  GenerationSession: 'GenerationSession',
  GenerationResult: 'GenerationResult',
  User: 'User',
} as const;
