/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * TeamPrompts.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export type ActivityEventType = typeof ActivityEventType[keyof typeof ActivityEventType];


export const ActivityEventType = {
  UserLoggedIn: 'UserLoggedIn',
  UserCreated: 'UserCreated',
  ScriptUploaded: 'ScriptUploaded',
  ScriptDeleted: 'ScriptDeleted',
  PromptCreated: 'PromptCreated',
  PromptDeleted: 'PromptDeleted',
  PromptVersionCreated: 'PromptVersionCreated',
  PromptVersionPromoted: 'PromptVersionPromoted',
  GenerationStarted: 'GenerationStarted',
  GenerationCompleted: 'GenerationCompleted',
  GenerationFailed: 'GenerationFailed',
  ResultCopied: 'ResultCopied',
  ResultFavorited: 'ResultFavorited',
  ResultUnfavorited: 'ResultUnfavorited',
} as const;
