/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * TeamPrompts.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PromptKind } from './promptKind';

export interface CreatePromptRequest {
  workspaceId: string;
  name: string;
  content: string;
  kind?: PromptKind;
  useKeywords?: boolean;
}
