/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * TeamPrompts.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export type FileType = typeof FileType[keyof typeof FileType];


export const FileType = {
  Pdf: 'Pdf',
  Txt: 'Txt',
} as const;
