/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * TeamPrompts.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ResultKind } from './resultKind';
import type { UserRef } from './userRef';

export interface GenerationResultDto {
  id: string;
  sessionId: string;
  index: number;
  content: string;
  kind: unknown | null | ResultKind;
  createdAt: string;
  isFavorite: boolean;
  favoriteCount: number;
  copyCount: number;
  isHighlighted: boolean;
  highlightedBy: unknown | null | UserRef;
  /** @nullable */
  highlightedAt: string | null;
}
