/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * TeamPrompts.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ActivityEventType } from './activityEventType';

export type GetApiActivityParams = {
skip?: number;
take?: number;
userId?: string;
type?: ActivityEventType;
};
