/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * TeamPrompts.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export type PostApiScriptProjectsBody = {
  workspaceId?: string;
} & {
  ContentType?: string;
  ContentDisposition?: string;
  Headers?: {[key: string]: string[]};
  Length?: number;
  Name?: string;
  FileName?: string;
} & {
  name?: string;
};
