/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * TeamPrompts.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiWorkspacesIdAvatarBodyHeaders } from './postApiWorkspacesIdAvatarBodyHeaders';

export type PostApiWorkspacesIdAvatarBody = {
  ContentType?: string;
  ContentDisposition?: string;
  Headers?: PostApiWorkspacesIdAvatarBodyHeaders;
  Length?: number;
  Name?: string;
  FileName?: string;
};
