/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * TeamPrompts.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PromptVersionDto } from './promptVersionDto';
import type { UserRef } from './userRef';

export interface PromptDetailDto {
  id: string;
  name: string;
  /** @nullable */
  mainVersionId: string | null;
  createdBy: UserRef;
  createdAt: string;
  updatedAt: string;
  versions: PromptVersionDto[];
}
