/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * TeamPrompts.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export type PromptKind = typeof PromptKind[keyof typeof PromptKind];


export const PromptKind = {
  Metadata: 'Metadata',
  ScriptTransform: 'ScriptTransform',
} as const;
