/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * TeamPrompts.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PromptKind } from './promptKind';
import type { UserRef } from './userRef';

export interface PromptListItemDto {
  id: string;
  name: string;
  /** @nullable */
  mainVersionId: string | null;
  createdBy: UserRef;
  createdAt: string;
  updatedAt: string;
  versionCount: number;
  kind: PromptKind;
  useKeywords: boolean;
  useSummarySource: boolean;
}
