/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * TeamPrompts.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export type ResultKind = typeof ResultKind[keyof typeof ResultKind];


export const ResultKind = {
  Title: 'Title',
  Description: 'Description',
  Hook: 'Hook',
  Tags: 'Tags',
  Thumbnail: 'Thumbnail',
} as const;
