/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * TeamPrompts.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { CanvasNodeDto } from './canvasNodeDto';

export interface SaveCanvasRequest {
  nodes: CanvasNodeDto[];
}
