/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * TeamPrompts.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { FileType } from './fileType';
import type { ScriptKind } from './scriptKind';
import type { SessionStatus } from './sessionStatus';
import type { UserRef } from './userRef';

export interface ScriptDto {
  id: string;
  name: string;
  originalFileName: string;
  fileType: FileType;
  extractedText: string;
  createdAt: string;
  updatedAt: string;
  createdBy: UserRef;
  /** @nullable */
  projectId: string | null;
  kind: ScriptKind;
  /** @nullable */
  sourceScriptId: string | null;
  /** @nullable */
  sourcePromptVersionId: string | null;
  /** @nullable */
  model: string | null;
  variantStatus: unknown | null | SessionStatus;
  /** @nullable */
  variantError: string | null;
}
