/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * TeamPrompts.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export type ScriptKind = typeof ScriptKind[keyof typeof ScriptKind];


export const ScriptKind = {
  Original: 'Original',
  Variant: 'Variant',
  Keywords: 'Keywords',
  Summary: 'Summary',
} as const;
