/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * TeamPrompts.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { FileType } from './fileType';
import type { UserRef } from './userRef';

export interface ScriptDto {
  id: string;
  name: string;
  originalFileName: string;
  fileType: FileType;
  extractedText: string;
  createdAt: string;
  updatedAt: string;
  createdBy: UserRef;
}
