/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * TeamPrompts.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { UserRef } from './userRef';

export interface ScriptProjectListItemDto {
  id: string;
  workspaceId: string;
  name: string;
  /** @nullable */
  originalScriptId: string | null;
  sortOrder: number;
  variantCount: number;
  createdBy: UserRef;
  createdAt: string;
  updatedAt: string;
}
