/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * TeamPrompts.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SessionStatus } from './sessionStatus';
import type { UserRef } from './userRef';

export interface SessionDto {
  id: string;
  /** @nullable */
  runId: string | null;
  scriptId: string;
  promptId: string;
  promptVersionId: string;
  promptName: string;
  model: string;
  status: SessionStatus;
  /** @nullable */
  error: string | null;
  createdBy: UserRef;
  createdAt: string;
  /** @nullable */
  completedAt: string | null;
}
