/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * TeamPrompts.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export type SessionStatus = typeof SessionStatus[keyof typeof SessionStatus];


export const SessionStatus = {
  Queued: 'Queued',
  Streaming: 'Streaming',
  Completed: 'Completed',
  Failed: 'Failed',
} as const;
