/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * TeamPrompts.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface UserAggregatesDto {
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  totalCostUsd: number;
  totalTokens: number;
  generationCount: number;
  failedCount: number;
  copyCount: number;
  favoriteCount: number;
  /** @nullable */
  lastActiveAt: string | null;
}
