/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * TeamPrompts.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface UserRef {
  id: string;
  displayName: string;
  /** @nullable */
  email?: string | null;
}
