/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * TeamPrompts.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ActivityEventDto } from './activityEventDto';
import type { UserAggregatesDto } from './userAggregatesDto';
import type { UserRef } from './userRef';

export interface UserProfileDto {
  user: UserRef;
  roles: string[];
  stats: UserAggregatesDto;
  recentActivity: ActivityEventDto[];
}
