/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * TeamPrompts.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateGenerationRequest,
  GenerationRunDto,
  RegenerateRequest,
  SessionDto,
  SessionWithResultsDto
} from '../../model';

import { customInstance } from '../../../lib/api/axios-instance';
import type { ErrorType , BodyType } from '../../../lib/api/axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const postApiGeneration = (
    createGenerationRequest: BodyType<CreateGenerationRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GenerationRunDto>(
      {url: `/api/generation`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createGenerationRequest, signal
    },
      options);
    }



export const getPostApiGenerationMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiGeneration>>, TError,{data: BodyType<CreateGenerationRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiGeneration>>, TError,{data: BodyType<CreateGenerationRequest>}, TContext> => {

const mutationKey = ['postApiGeneration'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiGeneration>>, {data: BodyType<CreateGenerationRequest>}> = (props) => {
          const {data} = props ?? {};

          return  postApiGeneration(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiGenerationMutationResult = NonNullable<Awaited<ReturnType<typeof postApiGeneration>>>
    export type PostApiGenerationMutationBody = BodyType<CreateGenerationRequest>
    export type PostApiGenerationMutationError = ErrorType<unknown>

    export const usePostApiGeneration = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiGeneration>>, TError,{data: BodyType<CreateGenerationRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiGeneration>>,
        TError,
        {data: BodyType<CreateGenerationRequest>},
        TContext
      > => {
      return useMutation(getPostApiGenerationMutationOptions(options), queryClient);
    }
    export const postApiGenerationSessionsSessionIdRegenerate = (
    sessionId: string,
    regenerateRequest: BodyType<RegenerateRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<SessionDto>(
      {url: `/api/generation/sessions/${sessionId}/regenerate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: regenerateRequest, signal
    },
      options);
    }



export const getPostApiGenerationSessionsSessionIdRegenerateMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiGenerationSessionsSessionIdRegenerate>>, TError,{sessionId: string;data: BodyType<RegenerateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiGenerationSessionsSessionIdRegenerate>>, TError,{sessionId: string;data: BodyType<RegenerateRequest>}, TContext> => {

const mutationKey = ['postApiGenerationSessionsSessionIdRegenerate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiGenerationSessionsSessionIdRegenerate>>, {sessionId: string;data: BodyType<RegenerateRequest>}> = (props) => {
          const {sessionId,data} = props ?? {};

          return  postApiGenerationSessionsSessionIdRegenerate(sessionId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiGenerationSessionsSessionIdRegenerateMutationResult = NonNullable<Awaited<ReturnType<typeof postApiGenerationSessionsSessionIdRegenerate>>>
    export type PostApiGenerationSessionsSessionIdRegenerateMutationBody = BodyType<RegenerateRequest>
    export type PostApiGenerationSessionsSessionIdRegenerateMutationError = ErrorType<unknown>

    export const usePostApiGenerationSessionsSessionIdRegenerate = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiGenerationSessionsSessionIdRegenerate>>, TError,{sessionId: string;data: BodyType<RegenerateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiGenerationSessionsSessionIdRegenerate>>,
        TError,
        {sessionId: string;data: BodyType<RegenerateRequest>},
        TContext
      > => {
      return useMutation(getPostApiGenerationSessionsSessionIdRegenerateMutationOptions(options), queryClient);
    }
    export const getApiGenerationSessionsSessionId = (
    sessionId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<SessionWithResultsDto>(
      {url: `/api/generation/sessions/${sessionId}`, method: 'GET', signal
    },
      options);
    }




export const getGetApiGenerationSessionsSessionIdQueryKey = (sessionId: string,) => {
    return [
    `/api/generation/sessions/${sessionId}`
    ] as const;
    }


export const getGetApiGenerationSessionsSessionIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiGenerationSessionsSessionId>>, TError = ErrorType<unknown>>(sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiGenerationSessionsSessionId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiGenerationSessionsSessionIdQueryKey(sessionId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiGenerationSessionsSessionId>>> = ({ signal }) => getApiGenerationSessionsSessionId(sessionId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: sessionId !== null && sessionId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiGenerationSessionsSessionId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiGenerationSessionsSessionIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiGenerationSessionsSessionId>>>
export type GetApiGenerationSessionsSessionIdQueryError = ErrorType<unknown>


export function useGetApiGenerationSessionsSessionId<TData = Awaited<ReturnType<typeof getApiGenerationSessionsSessionId>>, TError = ErrorType<unknown>>(
 sessionId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiGenerationSessionsSessionId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiGenerationSessionsSessionId>>,
          TError,
          Awaited<ReturnType<typeof getApiGenerationSessionsSessionId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiGenerationSessionsSessionId<TData = Awaited<ReturnType<typeof getApiGenerationSessionsSessionId>>, TError = ErrorType<unknown>>(
 sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiGenerationSessionsSessionId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiGenerationSessionsSessionId>>,
          TError,
          Awaited<ReturnType<typeof getApiGenerationSessionsSessionId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiGenerationSessionsSessionId<TData = Awaited<ReturnType<typeof getApiGenerationSessionsSessionId>>, TError = ErrorType<unknown>>(
 sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiGenerationSessionsSessionId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiGenerationSessionsSessionId<TData = Awaited<ReturnType<typeof getApiGenerationSessionsSessionId>>, TError = ErrorType<unknown>>(
 sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiGenerationSessionsSessionId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiGenerationSessionsSessionIdQueryOptions(sessionId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






