/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * TeamPrompts.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ActivityFeedDto,
  GetApiActivityParams,
  GetApiActivityUsersUserIdProfileParams,
  UserProfileDto
} from '../../model';

import { customInstance } from '../../../lib/api/axios-instance';
import type { ErrorType } from '../../../lib/api/axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getApiActivity = (
    params?: GetApiActivityParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ActivityFeedDto>(
      {url: `/api/activity`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiActivityQueryKey = (params?: GetApiActivityParams,) => {
    return [
    `/api/activity`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiActivityQueryOptions = <TData = Awaited<ReturnType<typeof getApiActivity>>, TError = ErrorType<unknown>>(params?: GetApiActivityParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiActivity>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiActivityQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiActivity>>> = ({ signal }) => getApiActivity(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiActivity>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiActivityQueryResult = NonNullable<Awaited<ReturnType<typeof getApiActivity>>>
export type GetApiActivityQueryError = ErrorType<unknown>


export function useGetApiActivity<TData = Awaited<ReturnType<typeof getApiActivity>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiActivityParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiActivity>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiActivity>>,
          TError,
          Awaited<ReturnType<typeof getApiActivity>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiActivity<TData = Awaited<ReturnType<typeof getApiActivity>>, TError = ErrorType<unknown>>(
 params?: GetApiActivityParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiActivity>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiActivity>>,
          TError,
          Awaited<ReturnType<typeof getApiActivity>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiActivity<TData = Awaited<ReturnType<typeof getApiActivity>>, TError = ErrorType<unknown>>(
 params?: GetApiActivityParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiActivity>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiActivity<TData = Awaited<ReturnType<typeof getApiActivity>>, TError = ErrorType<unknown>>(
 params?: GetApiActivityParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiActivity>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiActivityQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApiActivityUsersUserIdProfile = (
    userId: string,
    params?: GetApiActivityUsersUserIdProfileParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<UserProfileDto>(
      {url: `/api/activity/users/${userId}/profile`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiActivityUsersUserIdProfileQueryKey = (userId: string,
    params?: GetApiActivityUsersUserIdProfileParams,) => {
    return [
    `/api/activity/users/${userId}/profile`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiActivityUsersUserIdProfileQueryOptions = <TData = Awaited<ReturnType<typeof getApiActivityUsersUserIdProfile>>, TError = ErrorType<unknown>>(userId: string,
    params?: GetApiActivityUsersUserIdProfileParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiActivityUsersUserIdProfile>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiActivityUsersUserIdProfileQueryKey(userId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiActivityUsersUserIdProfile>>> = ({ signal }) => getApiActivityUsersUserIdProfile(userId,params, requestOptions, signal);





   return  { queryKey, queryFn, enabled: userId !== null && userId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiActivityUsersUserIdProfile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiActivityUsersUserIdProfileQueryResult = NonNullable<Awaited<ReturnType<typeof getApiActivityUsersUserIdProfile>>>
export type GetApiActivityUsersUserIdProfileQueryError = ErrorType<unknown>


export function useGetApiActivityUsersUserIdProfile<TData = Awaited<ReturnType<typeof getApiActivityUsersUserIdProfile>>, TError = ErrorType<unknown>>(
 userId: string,
    params: undefined |  GetApiActivityUsersUserIdProfileParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiActivityUsersUserIdProfile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiActivityUsersUserIdProfile>>,
          TError,
          Awaited<ReturnType<typeof getApiActivityUsersUserIdProfile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiActivityUsersUserIdProfile<TData = Awaited<ReturnType<typeof getApiActivityUsersUserIdProfile>>, TError = ErrorType<unknown>>(
 userId: string,
    params?: GetApiActivityUsersUserIdProfileParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiActivityUsersUserIdProfile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiActivityUsersUserIdProfile>>,
          TError,
          Awaited<ReturnType<typeof getApiActivityUsersUserIdProfile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiActivityUsersUserIdProfile<TData = Awaited<ReturnType<typeof getApiActivityUsersUserIdProfile>>, TError = ErrorType<unknown>>(
 userId: string,
    params?: GetApiActivityUsersUserIdProfileParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiActivityUsersUserIdProfile>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiActivityUsersUserIdProfile<TData = Awaited<ReturnType<typeof getApiActivityUsersUserIdProfile>>, TError = ErrorType<unknown>>(
 userId: string,
    params?: GetApiActivityUsersUserIdProfileParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiActivityUsersUserIdProfile>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiActivityUsersUserIdProfileQueryOptions(userId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






