/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * TeamPrompts.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreatePromptRequest,
  CreateVersionRequest,
  PromptDetailDto,
  PromptListItemDto,
  PromptVersionDto,
  UpdatePromptRequest
} from '../../model';

import { customInstance } from '../../../lib/api/axios-instance';
import type { ErrorType , BodyType } from '../../../lib/api/axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getApiPrompts = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PromptListItemDto[]>(
      {url: `/api/prompts`, method: 'GET', signal
    },
      options);
    }




export const getGetApiPromptsQueryKey = () => {
    return [
    `/api/prompts`
    ] as const;
    }


export const getGetApiPromptsQueryOptions = <TData = Awaited<ReturnType<typeof getApiPrompts>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPrompts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPromptsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPrompts>>> = ({ signal }) => getApiPrompts(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiPrompts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPromptsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPrompts>>>
export type GetApiPromptsQueryError = ErrorType<unknown>


export function useGetApiPrompts<TData = Awaited<ReturnType<typeof getApiPrompts>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPrompts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPrompts>>,
          TError,
          Awaited<ReturnType<typeof getApiPrompts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPrompts<TData = Awaited<ReturnType<typeof getApiPrompts>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPrompts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPrompts>>,
          TError,
          Awaited<ReturnType<typeof getApiPrompts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPrompts<TData = Awaited<ReturnType<typeof getApiPrompts>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPrompts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiPrompts<TData = Awaited<ReturnType<typeof getApiPrompts>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPrompts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPromptsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const postApiPrompts = (
    createPromptRequest: BodyType<CreatePromptRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PromptDetailDto>(
      {url: `/api/prompts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPromptRequest, signal
    },
      options);
    }



export const getPostApiPromptsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiPrompts>>, TError,{data: BodyType<CreatePromptRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiPrompts>>, TError,{data: BodyType<CreatePromptRequest>}, TContext> => {

const mutationKey = ['postApiPrompts'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiPrompts>>, {data: BodyType<CreatePromptRequest>}> = (props) => {
          const {data} = props ?? {};

          return  postApiPrompts(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiPromptsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiPrompts>>>
    export type PostApiPromptsMutationBody = BodyType<CreatePromptRequest>
    export type PostApiPromptsMutationError = ErrorType<unknown>

    export const usePostApiPrompts = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiPrompts>>, TError,{data: BodyType<CreatePromptRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiPrompts>>,
        TError,
        {data: BodyType<CreatePromptRequest>},
        TContext
      > => {
      return useMutation(getPostApiPromptsMutationOptions(options), queryClient);
    }
    export const getApiPromptsId = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PromptDetailDto>(
      {url: `/api/prompts/${id}`, method: 'GET', signal
    },
      options);
    }




export const getGetApiPromptsIdQueryKey = (id: string,) => {
    return [
    `/api/prompts/${id}`
    ] as const;
    }


export const getGetApiPromptsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiPromptsId>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPromptsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPromptsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPromptsId>>> = ({ signal }) => getApiPromptsId(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiPromptsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPromptsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPromptsId>>>
export type GetApiPromptsIdQueryError = ErrorType<unknown>


export function useGetApiPromptsId<TData = Awaited<ReturnType<typeof getApiPromptsId>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPromptsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPromptsId>>,
          TError,
          Awaited<ReturnType<typeof getApiPromptsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPromptsId<TData = Awaited<ReturnType<typeof getApiPromptsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPromptsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPromptsId>>,
          TError,
          Awaited<ReturnType<typeof getApiPromptsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPromptsId<TData = Awaited<ReturnType<typeof getApiPromptsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPromptsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiPromptsId<TData = Awaited<ReturnType<typeof getApiPromptsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPromptsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPromptsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const putApiPromptsId = (
    id: string,
    updatePromptRequest: BodyType<UpdatePromptRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PromptDetailDto>(
      {url: `/api/prompts/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updatePromptRequest, signal
    },
      options);
    }



export const getPutApiPromptsIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiPromptsId>>, TError,{id: string;data: BodyType<UpdatePromptRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiPromptsId>>, TError,{id: string;data: BodyType<UpdatePromptRequest>}, TContext> => {

const mutationKey = ['putApiPromptsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiPromptsId>>, {id: string;data: BodyType<UpdatePromptRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiPromptsId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiPromptsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiPromptsId>>>
    export type PutApiPromptsIdMutationBody = BodyType<UpdatePromptRequest>
    export type PutApiPromptsIdMutationError = ErrorType<unknown>

    export const usePutApiPromptsId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiPromptsId>>, TError,{id: string;data: BodyType<UpdatePromptRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiPromptsId>>,
        TError,
        {id: string;data: BodyType<UpdatePromptRequest>},
        TContext
      > => {
      return useMutation(getPutApiPromptsIdMutationOptions(options), queryClient);
    }
    export const deleteApiPromptsId = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/prompts/${id}`, method: 'DELETE', signal
    },
      options);
    }



export const getDeleteApiPromptsIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiPromptsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiPromptsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiPromptsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiPromptsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiPromptsId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiPromptsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiPromptsId>>>

    export type DeleteApiPromptsIdMutationError = ErrorType<unknown>

    export const useDeleteApiPromptsId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiPromptsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiPromptsId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteApiPromptsIdMutationOptions(options), queryClient);
    }
    export const postApiPromptsIdVersions = (
    id: string,
    createVersionRequest: BodyType<CreateVersionRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PromptVersionDto>(
      {url: `/api/prompts/${id}/versions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createVersionRequest, signal
    },
      options);
    }



export const getPostApiPromptsIdVersionsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiPromptsIdVersions>>, TError,{id: string;data: BodyType<CreateVersionRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiPromptsIdVersions>>, TError,{id: string;data: BodyType<CreateVersionRequest>}, TContext> => {

const mutationKey = ['postApiPromptsIdVersions'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiPromptsIdVersions>>, {id: string;data: BodyType<CreateVersionRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiPromptsIdVersions(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiPromptsIdVersionsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiPromptsIdVersions>>>
    export type PostApiPromptsIdVersionsMutationBody = BodyType<CreateVersionRequest>
    export type PostApiPromptsIdVersionsMutationError = ErrorType<unknown>

    export const usePostApiPromptsIdVersions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiPromptsIdVersions>>, TError,{id: string;data: BodyType<CreateVersionRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiPromptsIdVersions>>,
        TError,
        {id: string;data: BodyType<CreateVersionRequest>},
        TContext
      > => {
      return useMutation(getPostApiPromptsIdVersionsMutationOptions(options), queryClient);
    }
    export const postApiPromptsIdVersionsVersionIdPromote = (
    id: string,
    versionId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PromptDetailDto>(
      {url: `/api/prompts/${id}/versions/${versionId}/promote`, method: 'POST', signal
    },
      options);
    }



export const getPostApiPromptsIdVersionsVersionIdPromoteMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiPromptsIdVersionsVersionIdPromote>>, TError,{id: string;versionId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiPromptsIdVersionsVersionIdPromote>>, TError,{id: string;versionId: string}, TContext> => {

const mutationKey = ['postApiPromptsIdVersionsVersionIdPromote'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiPromptsIdVersionsVersionIdPromote>>, {id: string;versionId: string}> = (props) => {
          const {id,versionId} = props ?? {};

          return  postApiPromptsIdVersionsVersionIdPromote(id,versionId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiPromptsIdVersionsVersionIdPromoteMutationResult = NonNullable<Awaited<ReturnType<typeof postApiPromptsIdVersionsVersionIdPromote>>>

    export type PostApiPromptsIdVersionsVersionIdPromoteMutationError = ErrorType<unknown>

    export const usePostApiPromptsIdVersionsVersionIdPromote = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiPromptsIdVersionsVersionIdPromote>>, TError,{id: string;versionId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiPromptsIdVersionsVersionIdPromote>>,
        TError,
        {id: string;versionId: string},
        TContext
      > => {
      return useMutation(getPostApiPromptsIdVersionsVersionIdPromoteMutationOptions(options), queryClient);
    }
